services:
  postgres_container:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: f1rstdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: